version: '2'
services:
  moodle:
    container_name: moodle
    image: docker.io/bitnami/moodle:3
    ports:
      - '8080:8080'
    environment:
      - MOODLE_DATABASE_HOST=192.168.10.x4
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
#volumenes locales:    
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
#volumenes remotos en NFS Server    
#      - '/shares/moodle/moodle_data:/bitnami/moodle'
#      - '/shares/moodle/moodledata_data:/bitnami/moodledata'  
volumes:
  moodle_data:
    driver: local
  moodledata_data:
    driver: local